version: "3.9"
services:
    service:
        build:
            context: ./
            dockerfile: dockerfile
        container_name: service_facenet
        ports:
            - 2331:80
        restart: unless-stopped
        volumes:
            - /MLCV/services_center/facenet:/base
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: 1
                device_ids: ['2']
                capabilities: [gpu]
